version: "3.7"

services:

  django:
    container_name: "rocserver"
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`rocdata.global`, `www.rocdata.global`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
    ports:
      - 8000:8000
    command: ./manage.py runserver 0.0.0.0:8000
