version: "3.7"

services:

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--entrypoints.websecure.address=:443"
      # Receive docker events and automatically route to them based on labels
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@learningequality.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Redirect http --> https
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami_service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.rocdata.global`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  django:
    container_name: "rocserver"
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`rocdata.global`, `www.rocdata.global`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
    ports:
      - 8000:8000
    command: ./manage.py runserver 0.0.0.0:8000
